openapi: 3.0.3
info:
  title: ユーザ属性API
  version: 1.0.0
servers:
  - url: https://{domain}/user/api/v1
paths:
  /user_attr:
    post:
      tags: 
        - pip
      summary: ユーザ属性取得API
      description: |-
        PIP側で保持する指定されたユーザ属性を取得.<br>
        個人・事業者を区別せず全レコードが検索対象となる.<br>
        (対象外項目はnull返却(事業者情報の所属事業者など))
        検索条件未指定時は削除済みレコードを除き全件取得.<br>
        検索条件は以下いずれか1つのみ指定可能
        - リクエストボディ(from: 更新日時検索)
        - リクエストボディ(userIdList: PK(UUID)検索)
        - リクエストボディ(loginIdList: ログインID(メールアドレス)検索)
        ※リクエストボディでの検索条件指定となるためPOSTメソッドとしています
        ### アクセスが許可されている事業者/ユーザ
        - OpenFGAに"参照機能"のアクセス許可（認可タプル登録）されている事業者/ユーザ<br>
        （上記の事業者/ユーザを用いてL3-identity-componentから取得したアクセストークン(Authorization:Bearer)の設定が必須）

        ### ロールID定義
        #### 事業者
          - "1": 航路運営者
          - "2": 運航事業者
          - "3": 関係者
        #### ユーザ
          - "10": 航路運営者_責任者
          - "11": 航路運営者_担当者
          - "20": 運航事業者_責任者
          - "21": 運航事業者_担当者
      operationId: getUserAttr
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetUserAttrRequest"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetUserAttrResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseBadRequestError"
        "401":
          description: Un Authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseUnAuthorizedError"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseForbiddenError"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseNotFoundError"
        "415":
          description: Media Type Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseMediaTypeError"
        "500":
          description: Internal Server Error サーバーエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseInternalServerError"
    put:
      tags: 
        - pip
      summary: ユーザ属性更新API
      description: |-
        PIP側で保持する指定されたユーザの属性を更新.<br>
        操作ユーザ(Authorization:operateUid)と同一事業者所属のユーザのみ属性更新が可能<br>
        - 操作ユーザ(Authorization:operateUid)の指定が必須
        - 指定された以下項目の属性情報を更新する<br>(以下のいずれも指定しないか、いずれも既存から更新がない場合は400エラー返却)
          - login_user_id : ログインユーザID(メールアドレス)
          - operator_name : ユーザ名
          - attribute > roleIds : ロールID
        - "login_user_id"、"operator_name"を更新する場合、L3クレデンシャルへの事業者情報更新もあわせて実施する
        ### アクセスが許可されている事業者/ユーザ
        - OpenFGAに"登録/更新/削除機能"のアクセス許可（認可タプル登録）されている事業者/ユーザ<br>
        （上記の事業者/ユーザを用いてL3-identity-componentから取得したアクセストークン(Authorization:Bearer)の設定が必須）
        ### ロールID定義
        #### ユーザ
          - "10": 航路運営者_責任者
          - "11": 航路運営者_担当者
          - "20": 運航事業者_責任者
          - "21": 運航事業者_担当者
      operationId: putUserAttr
      security:
        - operateUid: []
        - bearerAuth: []
      parameters:
        - name: user_id
          in: query
          description: ユーザID,事業者ID(UUID)
          required: true
          schema:
            type: string
            default: available
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PutUserAttrRequest"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PutUserAttrResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseBadRequestError"
              example:
                code: 400
                errorMessage: 更新する項目を設定してください。
        "401":
          description: Un Authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseUnAuthorizedError"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseForbiddenError"
              example:
                code: 403
                errorMessage: ユーザ属性を更新する権限がありません。
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseNotFoundError"
              example:
                code: 404
                errorMessage: 指定されたuser_id(123e4567-e89b-12d3-a456-426614174000)は存在しません。
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseConflictError"
              example: 
                code: 409
                errorMessage: "指定したlogin_user_id(xxx@example.com)は既に存在しています。別のlogin_user_idを指定してください。"
        "415":
          description: Media Type Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseMediaTypeError"
        "500":
          description: Internal Server Error サーバーエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseInternalServerError"

  /admin/user_attr:
    put:
      tags: 
        - pip
      summary: ユーザ属性更新API (スーパーユーザ)
      description: |-
        PIP側で保持する指定された任意の事業者に所属するユーザの属性を更新.<br>
        - 指定された以下項目の属性情報を更新する<br>(以下のいずれも指定しないか、いずれも既存から更新がない場合は400エラー返却)
          - login_user_id : ログインユーザID(メールアドレス)
          - operator_name : ユーザ名
          - attribute > operatorId : 所属事業者ID
          - attribute > roleIds : ロールID
        - "login_user_id"、"operator_name"を更新する場合、L3クレデンシャルへの事業者情報更新もあわせて実施する
        ### アクセスが許可されている事業者/ユーザ
        - OpenFGAに"登録/更新/削除機能"のアクセス許可（認可タプル登録）されている事業者/ユーザ<br>
        （上記の事業者/ユーザを用いてL3-identity-componentから取得したアクセストークン(Authorization:Bearer)の設定が必須）
        ### ロールID定義
        #### ユーザ
          - "10": 航路運営者_責任者
          - "11": 航路運営者_担当者
          - "20": 運航事業者_責任者
          - "21": 運航事業者_担当者
      operationId: putUserAttrAdmin
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: query
          description: ユーザID,事業者ID(UUID)
          required: true
          schema:
            type: string
            default: available
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PutUserAttrAdminRequest"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PutUserAttrResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseBadRequestError"
              example:
                code: 400
                errorMessage: 更新する項目を設定してください。
        "401":
          description: Un Authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseUnAuthorizedError"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseForbiddenError"
              example:
                code: 403
                errorMessage: ユーザ属性を更新する権限がありません。
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseNotFoundError"
              example:
                code: 404
                errorMessage: 指定されたuser_id(123e4567-e89b-12d3-a456-426614174000)は存在しません。
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseConflictError"
              example: 
                code: 409
                errorMessage: "指定したlogin_user_id(xxx@example.com)は既に存在しています。別のlogin_user_idを指定してください。"
        "415":
          description: Media Type Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseMediaTypeError"
        "500":
          description: Internal Server Error サーバーエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseInternalServerError"

  /operator_attr:
    put:
      tags: 
        - pip
      summary: 事業者属性更新API
      description: |-
        PIP側で保持する指定された任意の事業者の属性を更新.<br>
        - 指定された以下のいずれかの属性情報を更新する<br>(以下のいずれも指定しないか、いずれも既存から更新がない場合は400エラー返却)
          - login_user_id : ログインユーザID(メールアドレス)
          - operator_name : ユーザ名
          - attribute > roleIds : ロールID
          - attribute > dipsAccountId : DIPSアカウントID
          - attribute > dipsAccountName : DIPSアカウント名
          - attribute > phone : 電話番号
          - attribute > swimOperatorId : SWIM連携用事業者ID(3桁)
        - "login_user_id"、"operator_name"、"swimOperatorId"を更新する場合、L3の事業者更新もあわせて実施する
        ### アクセスが許可されている事業者/ユーザ
        - OpenFGAに"登録/更新/削除機能"のアクセス許可（認可タプル登録）されている事業者/ユーザ<br>
        （上記の事業者/ユーザを用いてL3-identity-componentから取得したアクセストークン(Authorization:Bearer)の設定が必須）
        ### ロールID定義
        #### 事業者
          - "1": 航路運営者
          - "2": 運航事業者
          - "3": 関係者
      operationId: putOperatorAttr
      security:
        - bearerAuth: []
      parameters:
        - name: operator_id
          in: query
          description: ユーザID,事業者ID(UUID)
          required: true
          schema:
            type: string
            default: available
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PutOperatorAttrRequest"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PutOperatorAttrResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseBadRequestError"
              example:
                code: 400
                errorMessage: 更新する項目を設定してください。
        "401":
          description: Un Authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseUnAuthorizedError"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseForbiddenError"
              example:
                code: 403
                errorMessage: ユーザ属性を更新する権限がありません。
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseNotFoundError"
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseConflictError"
              example: 
                code: 409
                errorMessage: "指定したswimOperatorId(XXX)は既に存在しています。別のswimOperatorIdを指定してください。"
        "415":
          description: Media Type Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseMediaTypeError"
        "500":
          description: Internal Server Error サーバーエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/common.ResponseInternalServerError"


components:
  schemas:
    GetUserAttrRequest:
      type: object
      properties:
        from:
          description: |-
            更新日時(from:"yyyyMMdd-HHmmSS")<br>
            指定日時以降の更新レコードのみを返却します
          type: string
          example: 20250101-235959
        userIdList:
          type: array
          description: "PK(UUID)リスト"
          items:
            type: string
            description: 検索対象のuser_id(UUID)
        loginIdList:
          type: array
          description: "ログインIDリスト"
          items:
            type: string
            description: 検索対象のログインID

    PutUserAttrAdminRequest:
      type: object
      properties:
        login_user_id:
          type: string
          description: "ログインID(メールアドレス)"
          example: xxx@example.jp
        operator_name:
          type: string
          description: "ユーザ名"
        attribute:
          $ref: "#/components/schemas/PutUserAttrAdminParam"

    PutUserAttrRequest:
      type: object
      properties:
        login_user_id:
          type: string
          description: "ログインID(メールアドレス)"
          example: xxx@example.jp
        operator_name:
          type: string
          description: "ユーザ名"
        attribute:
          $ref: "#/components/schemas/PutUserAttrParam"

    PutOperatorAttrRequest:
      type: object
      properties:
        login_user_id:
          type: string
          description: "ログインID(メールアドレス)"
          example: xxx@example.jp
        operator_name:
          type: string
          description: "ユーザ名"
        attribute:
          $ref: "#/components/schemas/PutOperatorAttrParam"

    GetUserAttrResponse:
      type: object
      properties:
        attributeList:
          type: array
          items:
            type: object
            properties:
              user_id:
                type: string
                description: "PK(UUID)"
                example: "123e4567-e89b-12d3-a456-426614174000"
              user_login_id:
                type: string
                example: xxx@example.jp
              operator_name:
                type: string
              attribute:
                $ref: "#/components/schemas/UserAttrView"
            required:
              - user_id
              - user_login_id
              - operator_name
              - attribute

    PutUserAttrResponse:
      type: object
      properties:
        user_id:
          type: string
          description: "PK(UUID)"
          example: "123e4567-e89b-12d3-a456-426614174000"
        user_login_id:
          type: string
          example: xxx@example.jp
        operator_name:
          type: string
        attribute:
          $ref: "#/components/schemas/UpdateUserAttrView"
      required:
        - user_id
        - user_login_id
        - operator_name
        - attribute

    PutOperatorAttrResponse:
      type: object
      properties:
        user_id:
          type: string
          description: "PK(UUID)"
          example: "123e4567-e89b-12d3-a456-426614174000"
        user_login_id:
          type: string
          example: xxx@example.jp
        operator_name:
          type: string
        attribute:
          $ref: "#/components/schemas/UpdateOperatorAttrView"
      required:
        - user_id
        - user_login_id
        - operator_name
        - attribute

    UserAttrView:
      type: object
      properties:
        operatorId:
          type: string
          description: "所属事業者ID：UUID"
          example: "123e4567-e89b-12d3-a456-426614174000"
        roles:
          type: array
          description: "ロール（航路運営者_責任者/担当者、運航事業者_責任者/担当者）"
          items:
            type: object
            properties:
              roleId:
                type: string
              roleName:
                type: string
          example:
            - roleId: "10"
              roleName: "航路運営者_責任者"
            - roleId: "20"
              roleName: "運航事業者_責任者"
        dipsAccountId:
          type: string
        dipsAccountName:
          type: string
        phone:
          type: string
        swimOperatorId:
          type: string
        updateDatetime:
          type: string
          example: yyyyMMdd-HHmmSS
      required:
        - roles
        - updateDatetime

    UpdateUserAttrView:
      type: object
      properties:
        operatorId:
          type: string
          description: "所属事業者ID：UUID"
          example: "123e4567-e89b-12d3-a456-426614174000"
        roles:
          type: array
          description: "ロール（航路運営者_責任者/担当者、運航事業者_責任者/担当者）"
          items:
            type: object
            properties:
              roleId:
                type: string
              roleName:
                type: string
          example:
            - roleId: "10"
              roleName: "航路運営者_責任者"
            - roleId: "20"
              roleName: "運航事業者_責任者"
        updateDatetime:
          type: string
          example: yyyyMMdd-HHmmSS
      required:
        - roles
        - updateDatetime

    UpdateOperatorAttrView:
      type: object
      properties:
        roles:
          type: array
          description: "ロール（航路運営者_責任者/担当者、運航事業者_責任者/担当者）"
          items:
            type: object
            properties:
              roleId:
                type: string
              roleName:
                type: string
          example:
            - roleId: "10"
              roleName: "航路運営者_責任者"
            - roleId: "20"
              roleName: "運航事業者_責任者"
        dipsAccountId:
          type: string
        dipsAccountName:
          type: string
        phone:
          type: string
        swimOperatorId:
          type: string
        updateDatetime:
          type: string
          example: yyyyMMdd-HHmmSS
      required:
        - roles
        - dipsAccountId
        - dipsAccountName
        - phone
        - swimOperatorId
        - updateDatetime


#### 共通 ####
    UserAttrParam:
      type: object
      properties:
        operatorId:
          type: string
          description: |-
            所属事業者ID：UUID<br>
            以下の場合は設定不可
              - 利用用途1：操作ユーザと同一事業者所属のユーザの属性更新
              - 利用用途3：事業者の属性更新
          example: "123e4567-e89b-12d3-a456-426614174000"
        roleIds:
          type: array
          items: 
            type: string
          example:
            - "10"
            - "20"
        dipsAccountId:
          type: string
          description: |-
            DIPSアカウントID<br>
            以下の場合は設定不可
              - 利用用途1：操作ユーザと同一事業者所属のユーザの属性更新
              - 利用用途2：任意事業者所属のユーザの属性更新
        dipsAccountName:
          type: string
          description: |-
            DIPSアカウント名<br>
            以下の場合は設定不可
              - 利用用途1：操作ユーザと同一事業者所属のユーザの属性更新
              - 利用用途2：任意事業者所属のユーザの属性更新
        phone:
          type: string
          description: |-
            電話番号<br>
            以下の場合は設定不可
              - 利用用途1：操作ユーザと同一事業者所属のユーザの属性更新
              - 利用用途2：任意事業者所属のユーザの属性更新
        swimOperatorId:
          type: string
          description: |-
            SWIM連携用事業者ID(3桁)<br>
            以下の場合は設定不可
              - 利用用途1：操作ユーザと同一事業者所属のユーザの属性更新
              - 利用用途2：任意事業者所属のユーザの属性更新

    PutUserAttrAdminParam:
      type: object
      properties:
        operatorId:
          type: string
          description: |-
            所属事業者ID：UUID<br>
            以下の場合は設定不可
              - 利用用途1：操作ユーザと同一事業者所属のユーザの属性更新
          example: "123e4567-e89b-12d3-a456-426614174000"
        roleIds:
          type: array
          items: 
            type: string
          example:
            - "10"
            - "20"

    PutUserAttrParam:
      type: object
      properties:
        roleIds:
          type: array
          items: 
            type: string
          example:
            - "10"
            - "20"

    PutOperatorAttrParam:
      type: object
      properties:
        roleIds:
          type: array
          items: 
            type: string
          example:
            - "10"
            - "20"
        dipsAccountId:
          type: string
          description: |-
            DIPSアカウントID<br>
        dipsAccountName:
          type: string
          description: |-
            DIPSアカウント名<br>
        phone:
          type: string
          description: |-
            電話番号<br>
        swimOperatorId:
          type: string
          description: |-
            SWIM連携用事業者ID(3桁)<br>

    common.ResponseSuccess:
      description: オブジェクト
      type: object
    common.ResponseBadRequestError:
      description: エラーオブジェクト
      type: object
      properties:
        code:
          type: integer
          description: エラーの種類を示すエラーコード
          example: 400
        errorMessage:
          type: string
          description: エラーの説明
          example: "ユーザIDは必須項目です。"
      required:
        - code
        - errorMessage
    common.ResponseUnAuthorizedError:
      description: エラーオブジェクト
      type: object
      properties:
        code:
          type: integer
          description: エラーの種類を示すエラーコード
          example: 401
        errorMessage:
          type: string
          description: エラーの説明
          example: "アクセストークンの認証に失敗しました。"
      required:
        - code
        - errorMessage
    common.ResponseForbiddenError:
      description: エラーオブジェクト
      type: object
      properties:
        code:
          type: integer
          description: エラーの種類を示すエラーコード
          example: 403
        errorMessage:
          type: string
          description: エラーの説明
          example: "ユーザ属性を取得する権限がありません。"
      required:
        - code
        - errorMessage
    common.ResponseNotFoundError:
      description: エラーオブジェクト
      type: object
      properties:
        code:
          type: integer
          description: エラーの種類を示すエラーコード
          example: 404
        errorMessage:
          type: string
          description: エラーの説明
          example: "指定されたoperator_id(123e4567-e89b-12d3-a456-426614174000)は存在しません。"
      required:
        - code
        - errorMessage
    common.ResponseConflictError:
      description: エラーオブジェクト
      type: object
      properties:
        code:
          type: integer
          description: エラーの種類を示すエラーコード
          example: 409
        errorMessage:
          type: string
          description: エラーの説明
          example: "指定したlogin_user_id(123e4567-e89b-12d3-a456-426614174000)は既に存在しています。別のlogin_user_idを指定してください。"
      required:
        - code
        - errorMessage
    common.ResponseMediaTypeError:
      description: エラーオブジェクト
      type: object
      properties:
        code:
          type: integer
          description: エラーの種類を示すエラーコード
          example: 415
        errorMessage:
          type: string
          description: エラーの説明
          example: "適切なメディアタイプ(application/json)を指定してください。"
      required:
        - code
        - errorMessage
    common.ResponseInternalServerError:
      description: エラーオブジェクト
      type: object
      properties:
        code:
          type: integer
          description: エラーの種類を示すエラーコード
          example: 500
        errorMessage:
          type: string
          description: エラーの説明
          example: "予期しないシステムエラーが発生しました。"
      required:
        - code
        - errorMessage


  securitySchemes:
    # 操作ユーザUUID
    operateUid:
      type: http
      scheme: operateUid
    # アクセストークン
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
